CREATE TABLE diario (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START 10000),

    saver_id INT REFERENCES users (id) DEFAULT null,
    saved_on TIMESTAMP DEFAULT now(),

    quoted_id INT REFERENCES users (id) DEFAULT null,
    quoted_name VARCHAR DEFAULT null,

    warning TEXT DEFAULT null,
    quote TEXT NOT NULL,
    context TEXT DEFAULT null
);
